version: '3'
services:

  web:
    build: ./frontend
    # image: jfrevert/py-kube-web:latest
    # networks:
    # - frontend
    ports:
    - "9000:9000"

  app:
    build: ./app
    # image: jfrevert/py-kube-app:latest
    # networks:
    # - frontend
    # - backend
    ports:
    - "80:80"

  db:
    build: ./db
    # image: jfrevert/py-kube-db:latest
    ports:
    - "27017:27017"
    - "28017:28017"
    # networks:
    #   - backend
